version: '3'
services:
  nextjs:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default
    command: sh -c "pnpx prisma studio & pnpm dev"
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - default
volumes:
  db:
   driver: local
networks:
  default:
    

