-- CreateEnum
CREATE TYPE "Skills" AS ENUM ('KNOWLEDGEDEVELOPMENT', 'QUALITYPRODUCT', 'CREATINGOVERVIEW', 'CRITICALJUDGEMENT', 'COLLABORATION', 'COMMUNICATION', 'PLANNING', 'FLEXIBILITY', 'PROACTIVITY', 'REFLECTING');

-- AlterTable
ALTER TABLE "Reflection" ADD COLUMN     "skills" "Skills"[];
