import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Provider from "./_trpc/Provider";
import SideBar from "@/components/sidebar";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";

const inter = Poppins({weight: ["400", "500", "600", "700"], subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Reflekt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <Provider>
          <main className="w-screen h-screen fixed">
            <Navbar />
            <ResizablePanelGroup direction="horizontal">
              <ResizablePanel maxSize={30} defaultSize={15}>
                <SideBar />
              </ResizablePanel>
              <ResizableHandle withHandle />
              <ResizablePanel>{children}</ResizablePanel>
            </ResizablePanelGroup>
          </main>
        </Provider>
      </body>
    </html>
  );
}
